spring.application.name=notificationSender
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=paniz1390
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
firebase.config.path=classpath:firebase-adminsdk.json
logging.level.ir.project=DEBUG




